env:
  vue/setup-compiler-macros: true
extends:
- eslint:recommended
- plugin:vue/vue3-recommended
- plugin:@typescript-eslint/recommended
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
rules:
  indent:
  - warn
  - 2
  semi:
  - warn
  - never
  quotes:
  - warn
  - single
  comma-dangle:
  - warn
  - never
  vue/max-attributes-per-line: 'off'
  no-undef: 'off'
